### ISSUE TITLE
Does not work with Erlang 21

### ISSUE THREAD

**Issue by gotthardp** [emqtt/emqttc#62] opened 2018-07-01 00:10 UTC
The gen_logger crashes, probably due to https://github.com/emqtt/gen_logger/issues/5

Since mqttd uses lager, wouldn't it be better to get rid of the gen_logger and use lager instead?

**Comment by terry-xiaoyu** [comment] 2018-07-01 05:08
Yes, it is caused by the `parameterized module`. We'll update this project based on OTP 21 and release it as 'emqx-client' in EMQ R3.0.

**Comment by emqplus** [comment] 2018-07-02 00:51
@gotthardp This project will be upgraded to emqx-client, and released with EMQ X 3.0. The first tag will be ready this weekend.

**Comment by gotthardp** [comment] 2018-07-02 06:29
@emqplus Thanks a lot! That's perfect.

**Comment by manifest** [comment] 2018-07-09 04:58
@emqplus, is the release delayed?

**Comment by arpunk** [comment] 2018-08-01 01:01
I was not aware that lager was the consensus. I just submited #63 which removes gen_logger and relies on the Erlang modules for logging. I can switch to lager if there is interest.

**Comment by zhaoweiguo** [comment] 2018-08-01 02:07
@emqplus 
So when EMQ X 3.0 will be released?

**Comment by zhaoweiguo** [comment] 2018-08-02 03:44
@Gilbert-Wong 
Therefore, Since MQTT v5.0 is not backward compatible, we don't need to wait for the release of EMQ X 3.0

**Comment by Gilbert-Wong** [comment] 2018-08-02 03:46
Yes

**Comment by gotthardp** [comment] 2018-08-02 05:51
So, EMQ X 3.0 will support MQTT 5 only and this repository will continue to be used for MQTT 3.1? Do you plan any MQTT 3 related updates, or shall we propose updates for OTP 21? Will you at least continue to maintain this? (There are unaccepted pull requests for some time already.)

**Comment by Gilbert-Wong** [comment] 2018-08-02 06:01
Yes, this repository will be replaced with `emqx/emqx_client.erl` and both the implementation of mqtt v3.1 and mqtt v5.0 would be maintained.

**Comment by gotthardp** [comment] 2018-08-02 06:17
Replaced (emqx will support mqtt 3) or both this repository and emqx will continue exist in parallel?

**Comment by tkeksa** [comment] 2018-11-11 17:03
Do you plat to provide smaller client library or whole `emqx`  has to be used?

**Comment by Gilbert-Wong** [comment] 2018-11-12 00:30
We have schedule to provide smaller client library later.

**Comment by hommeabeil** [comment] 2019-04-29 15:16
I was looking in the source code and the history and I find [this commit](https://github.com/emqtt/emqttc/commit/9ccff9bd2d0b0e4095b6ec5af69384767cbbee8c). Does this fix this issue ?

**Comment by Gilbert-Wong** [comment] 2019-04-29 15:18
Nope, but it should work with erlang 21 now. You can try with it.

**Closed by Gilbert-Wong** 2019-04-29 15:18 UTC
Labels: question
